### ISSUE TITLE
Scrolling breaks when you scroll on header

### ISSUE THREAD

**Issue by timwis** [twbs/ratchet#138]
Forgive me if this is a known issue - I tried searching but couldn't find it.

I really look forward to using ratchet as an alternative to jQuery Mobile, but I seem to be having a major issue scrolling on my iPhone 5. The initial scrolling works fine, but if I drag the header, as if to scroll it down, that essentially breaks scrolling in the app until I refresh it. It starts scrolling the whole app instead of just the content area.

I've tried this on (1) my own basic ratchet page, (2) ratchet's dist/template.html page, and (3) junior's example, and all seem to have this issue. Am I doing something wrong or is this a known issue?

Thanks

**Comment by aetherwu** [comment]
@timwis 's solution works great.
