### ISSUE TITLE
Make push.js work on Phonegap

### ISSUE THREAD

**Issue by danitoto** [twbs/ratchet#553]
Hi! 

I search around but couldn´t find a good answer. Currently it´s not working in my test app, the links are "dead", however it works great on the browser. How could I make the transitions work with Phonegap? Any clue?

Thanks!

**Comment by olimortimer** [comment]
Would be great if you could share how you solved the problem @danitoto as it looks like a couple of us are experiencing the same issue

**Comment by trevor403** [comment]
You should use a plugin for cordova called cordova-httpd (Android and iOS) or local-webserver (iOS only)
