### ISSUE TITLE
Add option to destroy/disable slider

### ISSUE THREAD

**Issue by meleyal** [twbs/ratchet#587]
Currently the slider initializes itself on the `touchstart` event.

It would be nice to make this opt-in or have a way to disable it somehow (e.g. I'm thinking of how bootstrap's JS plugins work).

My use case is I want to use the slider for mobile, but turn it off for tablet/desktop (not using a script loader).

**Comment by occultskyrong** [comment]
ok, I have solved this problem , just delete the "class='slide'" from the element.

code like this
```
<div id="slider">
        <div class="slide-group">
            <div class="slide">
                <a href="#slide-2"></a>
                <img width="100%" src="/mobile/images/guide/1.jpg">
            </div>
            <div class="slide" id="slide-2">
                <a href="#slide-3"></a>
                <img width="100%" src="/mobile/images/guide/2.jpg">
            </div>
            <div class="slide" id="slide-3">
                <a href="#slide-4"></a>
                <img width="100%" src="/mobile/images/guide/3.jpg">
            </div>
            <div class="slide" id="slide-4">
                <a href="/mobile/store/home"></a>
                <img width="100%" src="/mobile/images/guide/4.jpg">
            </div>
        </div>
    </div>
```
e , I use a button to click and turn to next page.

**Comment by SumanRajSharma** [comment]
Return if toggle has **disabled** class. Add below code in all 3 event listener of toggle "touchstart", "touchmove" and "touchend".
`if(toggle.classList.contains('disabled')){
      return;
    }`
