### ISSUE TITLE
[SOLVED] How to fire a modal?

### ISSUE THREAD

**Issue by LC2712** [twbs/ratchet#602]
Hello,
I can't understand how to open a modal via JS (I want it to open as soon as document is loaded).
I also tried to trigger a touch/click event to the related link, but didn't work.

HELP!!!!!!!!!!!1111!!111!111!!!1!1!!!!!!

**Comment by pattyland** [comment]
This is not a good way... The Dialog is not fading in, and the normal button to close is not working anymore when the dialog os openend this way.
There should be something like Bootstraps functions for modals:
```javascript
$('#myModal').modal('toggle');
$('#myModal').modal('show');
$('#myModal').modal('hide');
```

**Comment by xygahs0801** [comment]
@pattyland I green.

**Comment by jgriffen** [comment]
@pattyland, I thought of the same thing. So, I built a custom jQuery function for this purpose. Here is what I came up with:

```javascript
/*
 * Displays or hides a Ratchet modal.
 *
 * USAGE:
 * $('#modelId').rmodal('show');
 */
$.fn.rmodal = function (display) {
    if (display === 'show') {
        $(this).show('slide', { direction: 'down' }, 1000).addClass('active');
    } else if (display === 'hide') {
        $(this).slideDown(function () {
            $(this).removeClass('active').hide();
        });
    } else {
        console.error('This type is not defined for opening a modal.');
    }
}
```

I also overrode the Ratchet functionality of displaying a modal with a link using this event:

```javascript
$('a[data-type="rmodal"]').on('click', function (e) {
    e.preventDefault();

    var elId = $(this).attr('id'),
        $el = $('#' + elId);

    if ($el.is(':visible')) {
        $('#' + elId).slideDown(function () {
            $(this).removeClass('active');
        });
    } else {
        $('#' + elId).slideUp().addClass('active');
    }
});
```

To use this, the only thing that needs to be changed on the modal links for Ratchet is adding a `data-type` attribute.

```html
<a href="#modalId" data-type="rmodal">Open Modal</a>
```
