### ISSUE TITLE
Page redirect failed when work with Angular Fullstack

### ISSUE THREAD

**Issue by neospio** [twbs/ratchet#645]
use angular-fullstack generator to bootstrap a simple angular project, then use bower install ratchet to install the latest ratchet package, the page redirection now fails on mobile phone or IOS simulators.
BTW, it works well on desktop browsers.

**Comment by paoloantinori** [comment]
Adding a comment here just to help search engines:

This trick is what allowed me to have ratchet working with Angular2 router.
