### ISSUE TITLE
Push and phonegap event page change not called.

### ISSUE THREAD

**Issue by rookmoot** [twbs/ratchet#667]
Hello,

I wrote a test application to try ratchet on phonegap. The main idea is the handle the "push" event to know when the application page change.

I tried some test without getting it running (on phonegap, ie. It's working on my chrome browser).

An exemple here in index.html :

```
<script type="text/javascript" charset="utf-8">
  window.addEventListener("push", function() {
    alert('change');
  });
  PUSH({url: 'dashboard.html', transition: 'slide-in'});
</script>
```

This is working fine on chrome but i can't get it working under my phonegap application, know why ?

Thank you.

**Comment by trevor403** [comment]
Call it inside your deviceready event handler
