### ISSUE TITLE
PUSH.js the android 4.0+ is not work

### ISSUE THREAD

**Issue by mtyang** [twbs/ratchet#693]
```js
window.addEventListener('push', function(){
	alert('test');
	require.graceInload();
});
```

This code under the android can't work, what should I do?

**Comment by Johann-S** [comment]
This is fixed since the merge of this PR https://github.com/twbs/ratchet/pull/748

**Comment by gdisanto** [comment]
I had the same problem that I solved by using the last ratchet.js version.
The push event is not fired the first time though. Is there any workaround for this?

**Comment by Johann-S** [comment]
The fix for this issue will be in the next release of Ratchet (2.1.0)

**Comment by gdisanto** [comment]
Thanks!

**Comment by cvrebert** [comment]
Closing since #748 has been merged.

**Comment by phil-imaginatik** [comment]
@gdisanto there's an additional issue with the 'fade' transition on android, which may be why your first push doesn't work properly. That occurred for me too. I changed everything to either a slide-in or slide-out and it's all working okay now.
