### ISSUE TITLE
Navigation doesn't work for locally hosted documentation

### ISSUE THREAD

**Issue by juriejan** [twbs/ratchet#737]
Instructions provided at https://github.com/twbs/ratchet#running-documentation-locally serves the main page fine at http://127.0.0.1:4000 but the navigation links at the top of the page don't seem to work. Almost like the Javascript that implements it isn't being loaded, which doesn't seem to be the case.

**Comment by cvrebert** [comment]
I'm getting 404s. It's linking to e.g. http://127.0.0.1:4000/getting-started/ instead of http://127.0.0.1:4000/getting-started.html

**Comment by juriejan** [comment]
Sorry, that was a bit vague. I'm also getting 404's which I believe it due to the links not being activated. The URL's seem fine to me as they work fine on the public site.

Perhaps the hosting configuration of the site is making these URL's work, and the links don't require any kind of activation.
