### ISSUE TITLE
Can't enter input form elements

### ISSUE THREAD

**Issue by Krysisx** [twbs/ratchet#768]
I have this HTML code:

```html
<form id="form">
	<p id='desc'></p>
	<input type="text" id="user" placeholder="Username" value="user" />
	<input type="password" id="pass" placeholder="Password" value="" />
	<span id="other"></span>
	<a id="login_btn" class="btn btn-positive btn-block">Login</a>
</form>
```

I was using ratchet 2.0.2 updated on 4th April 2014 and I decided to download and use the new current code.
Now I can't enter `<input>` elements when I'm on my smartphone and so the keyboard does not show up and I can't write anything.
The only way to enter `<input>` elements is to make a long tap (more than 1 sec) on an `<input>` element.
I'm using cordova and crosswalk so the webview that renders my application comes from crosswalk with its chromium based code.

The strange thing is that the following code works:

```html
<form id="search">
    <input type="search" id="search_input" placeholder="Search" />
    <span id="elem" class="icon icon-search"> </span>
</form>
```

So what's changed from v2.0.2 and the current versions that involves my HTML code?
Any help to solve it?

Thanks
Anyone can solve my problem? Thanks

**Comment by Krysisx** [comment]
Ok, I just tried to keep the latest .css file (from master) and go back to old .js file (stable version from website).
Now everything works, so the problem was with the .js file but I don't know why.

**Comment by Johann-S** [comment]
Can you provide the full code ? Where is your ``form`` ? Is it in a modal ?
