### ISSUE TITLE
Second page nav bars are not replacing initial nav bar on iOS

### ISSUE THREAD

**Issue by phillipsj** [twbs/ratchet#777]
So I have noticed this issue on iOS 8 with both mobile safari and chrome.  It was previously working, but for some reason now, my other pages are not putting the new pages nav bar on top of the original nav bar.  It still works on desktop browsers and when emulating, even works on Android.

Initial Page: 

```
<header class="bar bar-nav">
    <h1 class="title">Title</h1>
</header>
```

Second Page:

```
<div class="bar bar-nav">
    <a id="backButton" class="icon icon-left-nav pull-left" onclick="window.history.back()" data-    
         ignore="push">Back</a>
    <h1 class="title">Title</h1>
</div>
```

**Comment by aetherwu** [comment]
I've got the same problem when I swipe through pages.
