### ISSUE TITLE
Get blog posts fed straight into my news app

### ISSUE THREAD

**Issue by ac1502** [twbs/ratchet#807]
Hey to all at ratchet!

i have just discovered this genious library and was wondering if you can help me.

I have knowledge on HTML and CSS yet basic on JS.

So i am developing a news app based on my website http://coventryonline.net/

How can i automatically pull categorised blog posts into my news app? is there a ratchet js script for that?

Very much looking forward to your reply!

Navneet

**Comment by cvrebert** [comment]
Your question isn't particularly Ratchet-specific. Try asking it on a general web development forum instead. Good luck!
