### ISSUE TITLE
1 Modal not closing 

### ISSUE THREAD

**Issue by karimchedid** [twbs/ratchet#810]
I have this simple about page  http://www.techana.com/About  i used ratchet ios , and added 2 modals, the 1st modal open but when close it on X right side doesnt close i have to refresh the page, but the modal 2nd works fine without any problem ,

 <div>
    <header class="bar bar-nav">
      <h1 class="title">Our Apps </h1>
    </header>
    
    
    
    <div class="content">

     <a href="#kuwaiSigns" class="btn"><img src="img/kuwaitsigns.png" alt="HTML tutorial" width="100" height="100"> <br> Kuwait Signs</a>

     <a href="#tongueTwister" class="btn"><img src="img/tonguetwister.png" alt="HTML tutorial" width="100" height="100"> <br> Tongue Twister</a>

     

      <div id="kuwaiSigns" class="modal">
              <header class="bar bar-nav">
                <a class="icon icon-close pull-right" href="#kuwaitSigns"></a>
                <h1 class="title">Kuwait Signs</h1>
              </header>

                <div class="content">

                      <img class="icon-modal" src="img/kuwaitsigns.png" alt="HTML tutorial" width="100" height="100">

                      <p class="content-padded">KuwaitSigns is an application that aim to assist new applicants for Kuwaiti driving license and experienced professional drivers in the state of Kuwait, providing information about the sign system and the traffic laws including examples of the written exams and other helpful informations. <br>
                      <a href="https://itunes.apple.com/us/app/kuwait-signs-asharat-alkwyt/id855090600?mt=8"><img src="img/appstore.png"  alt="Appstore"></a></p>
            
                  </div>
        </div>

    <div id="tongueTwister" class="modal">
      <header class="bar bar-nav">
        <a class="icon icon-close pull-right" href="#tongueTwister"></a>
        <h1 class="title">Tongue Twister</h1>
      </header>

      <div class="content">

        <img class="icon-modal" src="img/tonguetwister.png" alt="HTML tutorial" width="100" height="100">

        <p class="content-padded">This App is a creative way to play tongue twisters, including video recording, enabling you to share your video, or your friend's videos in a very funny creative way, specially if you save the video with the chipmunk audio effect, try it yourself and have fun!!!. <br>
        <a href="https://itunes.apple.com/us/app/tonguetwister-say-it-fast!/id883679533?mt=8"><img src="img/appstore.png"  alt="Appstore"></a></p>
    
      </div>
    </div>

please Help

**Comment by vitaliyterziev** [comment]
There is typo in your html -> href="#kuwaitSigns" must be changed to href="#kuwaiSigns", i tested and works.
These questions are more suited for stackoverflow not here, please close the issue in order for the devs to be able to see the real bugs.

```
              <header class="bar bar-nav">
                <a class="icon icon-close pull-right" href="#kuwaitSigns"></a>
                <h1 class="title">Kuwait Signs</h1>
              </header>
```

**Comment by karimchedid** [comment]
thx a lot vitaliyterziev  ,
