### ISSUE TITLE
Link in docs is not working

### ISSUE THREAD

**Issue by selfrefactor** [twbs/ratchet#812]
From http://goratchet.com/getting-started/
3. Save the app to your phone
There are a few ways to do this, but the simplest is to run a local server on your computer, point Safari on your iPhone to your computer, then click the  button and "Add to Home Screen". For Android, check out **this guide**.

The issue is that the link of **this guide** is not a valid address and it seems like a important information.

**Comment by dimitri-bourreau** [comment]
Hi,

The initial link is : https://developers.google.com/chrome/mobile/docs/installtohomescreen

Seems like the link changed. 
Looking at the URL and the context, we want a Google Chrome documentation dedicated to add WPAs to the homescreen of an Android device locally for testing.
I believe this link is the one we want :
https://developers.google.com/web/tools/chrome-devtools/progressive-web-apps#add-to-homescreen

> If you want to test out the genuine mobile experience, you can connect a real mobile device to DevTools via [remote debugging]remote debugging, and then click the Add to Homescreen button (on DevTools) to trigger the "add to homescreen" prompt on the connected mobile device.

If I'm right, [I already forked the project and the PR can be done easily](https://github.com/tobudim/ratchet/commit/83627b51172c76b28b5f17d782cab334e57e3f90).

**Comment by selfrefactor** [comment]
I already forgot the context and the reason for opening this issue, but thanks anyway.

**Comment by dimitri-bourreau** [comment]
Context is what the page is about.
You closed this issue too fast, though here is the PR. ^

**Comment by selfrefactor** [comment]
Sorry for closing the issue prematurely.
