### ISSUE TITLE
push js not working, the problem are not the clicks

### ISSUE THREAD

**Issue by vitaliyterziev** [twbs/ratchet#813]
Uncaught TypeError: Cannot use 'in' operator to search for 'innerText' in null  - >  row 10 in min version

This is what i get when trying to push one html file with one P tag or DIV with class content and P tag inside.

**Comment by XhmikosR** [comment]
Please, make sure this happens with the latest master version.

**Comment by vitaliyterziev** [comment]
OK, i am going to try it but it is my understanding that the xhr push js works with "views" similar to Angular js. Just one html file with nothing more than content which will be placed in the "content" div, no head, html tag, body etc. The explanation in the docs is little bit vague, anyway there were similar errors with the original examples. I tried with full html page with all of its tags and sections and push js replaced my whole index.html file which wasnt good either.

**Comment by vitaliyterziev** [comment]
//data.title = head.querySelector('title');
    //var text = 'innerText' in data.title ? 'innerText' : 'textContent';
    //data.title = data.title && data.title[text].trim();

these 3 rows need to be striked out or fixed in order for push js to work. Since the query selector is returning null in cases where we do not have <head> tag and title respectively. If the rows below are not used there are no problems with the template below for example:
"
<header class="bar bar-nav">
    <span class="icon icon-bars"></span>
</header>

<div class="content">
    <p>THIS IS SOME RANDOM TEXT HERE!</p>
</div>

<footer class="bar bar-footer"></footer>
"

**Comment by XhmikosR** [comment]
@vitaliyterziev: please make a pull request with your proposed fix along with a test case.

**Comment by vitaliyterziev** [comment]
@XhmikosR nothing to do actually, just the push.js in the  web download http://goratchet.com/ is behind the  push.js version on github that is where the confusion comes from. When they are synced this should be fine. I am closing this down.  Thanks for your support!
