### ISSUE TITLE
使用jsp是不是不能使用h5+的功能？

### ISSUE THREAD

**Issue by sweetwangym** [twbs/ratchet#833]
开发用的java，请求返回的是jsp，不能使用h5+的功能，不知道有没有人遇到过这种问题，是不是和html5+runtime有关

**Comment by AlexLove77** [comment]
哥们你最好用英文来问，要不那些大牛也看不懂你问的啊。 You'd better ask in English.

---

His question: I develop with Java and return JSP, but I cannot use h5+ functions, does anyone have this problem? Is it related to the problem of html5+rutime?

**Comment by elveahuang** [comment]
一个外行的来回答下你这个问题，H5跟JSP没有冲突，JSP最终的显示就是HTML，至于版本，肯定是H5最好。H5跟Runtime无关，只跟浏览器是否支持有关。

**Comment by mazong1123** [comment]
The H5 features only impacted by Browsers, not JSP or any other render engine/tech. Please check your browser compatibility.

**Comment by cvrebert** [comment]
Unfortunately, we are unable to provide assistance in Chinese.
