### ISSUE TITLE
Can AnyOne explain what is push.js file exactly ? is that the same file come with phonegap or Cordova project ?

### ISSUE THREAD

**Issue by Toomavic** [twbs/ratchet#846]

**Comment by pattyland** [comment]
push.js is way of loading new pages via ajax without reloading the page.
cordova.js is a bridge to access non-browser features on mobile device via JavaScript

Do you even read the docs? http://goratchet.com/components/#push

**Comment by Toomavic** [comment]
I read the docs .. that's why I am asking 
is that the same file that exist in phonegap default project (index.js) ?
