### ISSUE TITLE
How to generate .apk file

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [twbs/ratchet#868]

**Comment by Milito007** [comment]
hello, Anyone has an idea on how I can connect my ratchet app to my Laravel back end?

**Comment by romarioj2h** [comment]
@mohammadayoub96 you have to use a framework like phonegap/cordova, ratchet is just a css framework.

**Comment by miladrahimi** [comment]
> hello, Anyone has an idea on how I can connect my ratchet app to my Laravel back end?

You have to do that using JavaScript AJAX
